# Main configuration file for team buildings and upgrade requirements
# Each team starts with these buildings at level 1 (unless otherwise specified)

# Town Hall - Main team building
[assets.townhall]
    name = "Town Hall"
    description = "The main goal is to upgrade this building."
    starting_level = 1
    max_level = 9
    icon = "🏰"

    # Upgrade requirements for Town Hall by level
    # Format: [level, "resource_name", amount]
    upgrade_costs = [
        # Level 2
        [2, "$category:bones", 500],
        [2, "coins", 100000],
        # Level 3
        [3, "zenyte shard", 3],
        [3, "dragon plateskirt", 1],
        # Level 4
        [4, "$category:dks rings", 10],
        [4, "iron ore", 300],
        [4, "$category:runes", 5000],
        # Level 5
        [5, "kbd heads", 2],
        [5, "runite ore", 200],
        [5, "yew logs", 4000],
        [5, "awakener's orb", 5],
        # Level 6
        [6, "$category:bandos uniques", 4],
        [6, "magic logs", 2500],
        [6, "iron ore", 1000],
        # Level 7
        [7, "$category:zulrah uniques", 3],
        [7, "$category:cerb crystals", 2],
        [7, "$category:gems", 5000],
        [7, "$category:seeds", 10000],
        [7, "clay", 1000],
        [7, "coins", 100000],
        [7, "soul rune", 10000],
        [7, "mithril ore", 2500],
        [7, "venator shard", 2],
        # Level 8
        [8, "$category:toa purple", 2],
        [8, "$category:araxxor uniques", 5],
        [8, "bones", 5000],
        [8, "crystal shard", 500],
        [8, "dragon axe", 3],
        [8, "coins", 1000000],
        [8, "awakener's orb", 20],
        # Level 9
        [9, "$category:cox purple", 2],
        [9, "$category:zammy uniques", 2],
        [9, "$category:seeds", 10000],
        [9, "coins", 2500000],
        [9, "$category:ores", 100000],
        [9, "$category:logs", 10000],
        [9, "vial of blood", 50],
    ]

# Armory - For weapon upgrades and team equipment
[assets.armory]
    name = "Armory"
    description = "Allows you to get drops from higher level monsters"
    starting_level = 1
    max_level = 9
    icon = "⚔️"

    # Upgrade requirements for Armory by level
    upgrade_costs = [

        # Level 2
        [2, "coins", 10000],
        [2, "&category:ores", 250],
        [2, "&category:runes", 500],
        [2, "bracelet of ethereum", 5],
        [2, "grapes", 1],
        # Level 3
        [3, "$category:herbs", 250],
        [3, "larran's key", 10],
        [3, "$category:seeds", 500],
        [3, "long bone", 1],
        [3, "mole claw", 5],
        # Level 4
        [4, "adamantite bar", 500],
        [4, "coins", 100000],
        [4, "$category:gems", 500],
        [4, "$category:lunar chest uniques", 500],
        # Level 5
        [5, "yew seed", 20],
        [5, "brimstone key", 25],
        [5, "ballista spring", 1],
        [5, "cheese", 1],
        # Level 6
        [6, "$category:colosseum uniques", 1],
        [6, "coins", 100000],
        [6, "kurask head", 1],
        [6, "$category:logs", 5000],
        [6, "kraken tentacle", 1],
        # Level 7
        [7, "$category:godsword shards", 2],
        [7, "coins", 250000],
        [7, "$category:gems", 1000],
        [7, "$category:ores", 6000],
        [7, "willow logs", 100],
        # Level 8
        [8, "$category:arma uniques", 2],
        [8, "$category:gems", 10000],
        [8, "giant egg sac", 5],
        # Level 9
        [9, "$category:colosseum uniques", 2],
        [9, "coins", 1000000],
        [9, "ancient totem", 2],
        [9, "$category:dks rings", 10],
        [9, "granite shield", 2],
        [9, "granite helm", 2],
    ]

[assets.slayer_master]
    name = "Slayer Master"
    description = "Allows you to get loot from monsters with slayer requirements"
    starting_level = 1
    max_level = 9
    icon = "🗡️"

    # Upgrade requirements for Slayer Master by level
    upgrade_costs = [
        # Level 2
        [2, "$category:ores", 100],
        [2, "bones", 100],
        [2, "scaly blue dragonhide", 5],
        # Level 3
        [3, "kurask head", 1],
        [3, "top of sceptre", 4],
        # Level 4
        [4, "$category:elder chaos robes", 6],
        [4, "long bone", 2],
        [4, "sunfire splinters", 10000],
        [4, "red spiders' eggs", 500],
        # Level 5
        [5, "adamant javelin", 1000],
        [5, "dragon 2h sword", 1],
        [5, "$category:gems", 500],
        [5, "coins", 50000],
        # Level 6
        [6, "onyx bolt tips", 1000],
        [6, "coins", 100000],
        [6, "$category:herbs", 1000],
        [6, "$category:toa purple", 1],
        # Level 7 - sire
        [7, "$category:tormented demon uniques", 2],
        [7, "$category:voidwaker pieces", 1],
        [7, "clue scroll (medium)", 10],
        [7, "coins", 200000],
        # Level 8
        [8, "saradomin's light", 2],
        [8, "coins", 300000],
        [8, "$category:toa purple", 1],
        # Level 9
        [9, "monkey tail", 1],
        [9, "coins", 500000],
    ]

# Treasury - For storing and managing team funds
[assets.treasury]
    name = "Treasury"
    description = "Multiplies coin drops"
    starting_level = 1
    max_level = 9
    icon = "💰"

    # Upgrade requirements for Treasury by level
    upgrade_costs = [
        [1, "$category:runes", 150],
        [1, "coins", 1000],
        # Level 2
        [2, "coins", 5000],
        [2, "$category:runes", 250],
        # Level 3
        [3, "ranarr seed", 20],
        [3, "coins", 20000],
        [3, "$category:ores", 500],
        # Level 4
        [4, "dragon javelin heads", 150],
        [4, "coins", 50000],
        # Level 5
        [5, "coins", 50000],
        [5, "$category:runes", 500],
        # Level 6
        [6, "chromium ingot", 1],
        # Level 7
        [7, "abyssal whip", 1],
        [7, "$category:runes", 5000],
        # Level 8
        [8, "sunfire splinters", 30000],
        # Level 9
        [9, "vial of blood", 10],
    ]

# Prospector's Shop - For enhancing mining resources
[assets.prospector_shop]
    name = "Prospector's Shop"
    description = "Multiplies ore drops"
    starting_level = 1
    max_level = 9
    icon = "⛏️"

    # Upgrade requirements for Prospector's Shop by level
    upgrade_costs = [
        [1, "bones", 1],
        # Level 2
        [2, "sapphire ring", 5],
        [2, "blood rune", 100],
        # Level 3
        [3, "magic logs", 100],
        # Level 4
        [4, "ancient staff", 1],
        # Level 5
        [5, "gold ore", 1000],
        # Level 6
        [6, "coins", 100000],
        # Level 7
        [7, "rune boots", 5],
        # Level 8
        [8, "coins", 300000],
        # Level 9
        [9, "dragon arrowtips", 500],
    ]

# Herbalist's Hut - For enhancing herblore resources
[assets.herbalist_hut]
    name = "Herbalist's Hut"
    description = "Multiplies herb drops"
    starting_level = 1
    max_level = 9
    icon = "🌿"

    # Upgrade requirements for Herbalist's Hut by level
    upgrade_costs = [
        [1, "$category:bones", 100],
        # Level 2
        [2, "grimy guam", 2],
        # Level 3
        [3, "grimy marrentil", 5],
        # Level 4
        [4, "splitbark legs", 2],
        # Level 5
        [5, "unidentified small fossil", 25],
        # Level 6
        [6, "crystal key", 2],
        # Level 7
        [7, "glacial temotli", 2],
        # Level 8
        [8, "dragon halberd", 4],
        # Level 9
        [9, "guam seed", 1000],
    ]

# Woodcutter's Lodge - For enhancing woodcutting resources
[assets.woodcutter_lodge]
    name = "Woodcutter's Lodge"
    description = "Multiplies log drops"
    starting_level = 1
    max_level = 9
    icon = "🪓"

    # Upgrade requirements for Woodcutter's Lodge by level
    upgrade_costs = [
        [1, "$category:gems", 10],
        # Level 2
        [2, "$category:runes", 750],
        # Level 3
        [3, "nature rune", 1000],
        # Level 4
        [4, "oak plank", 200],
        # Level 5
        [5, "mahogany plank", 400],
        # Level 6
        [6, "berserker ring", 1],
        # Level 7
        [7, "seers ring", 1],
        # Level 8
        [8, "light frame", 1],
        # Level 9
        [9, "aranea boots", 1],
    ]

# Farming Guild - For enhancing farming resources
[assets.farming_guild]
    name = "Farming Guild"
    description = "Multiplies seed drops"
    starting_level = 1
    max_level = 9
    icon = "🌱"

    # Upgrade requirements for Farming Guild by level
    upgrade_costs = [
        [1, "$category:runes", 100],
        [1, "$category:seeds", 50],
        [1, "coins", 1000],
        # Level 2
        [2, "$category:herbs", 100],
        [2, "$category:coins", 25000],
        # Level 3
        [3, "iron halberd", 2],
        [3, "body rune", 5000],
        # Level 4
        [4, "coins", 100000],
        # Level 5
        [5, "coins", 200000],
        # Level 6
        [6, "mole skin", 200],
        # Level 7
        [7, "lily of the sands", 200],
        # Level 8
        [8, "coins", 300000],
        # Level 9
        [9, "bottomless compost bucket", 160],
    ]


# Magic Workshop - For enhancing runecrafting and enchanting
[assets.rune_shop]
    name = "Rune Shop"
    description = "Multiplies rune drops"
    starting_level = 1
    max_level = 9
    icon = "✨"

    # Upgrade requirements for Magic Workshop by level
    upgrade_costs = [
        [1, "$category:herbs", 50],
        # Level 2
        [2, "steel bar", 50],
        # Level 3
        [3, "mahogany logs", 123],
        # Level 4
        [4, "zombie pirate key", 10],
        # Level 5
        [5, "sinister key", 2],
        # Level 6
        [6, "mole claw", 100],
        # Level 7
        [7, "dark claw", 1],
        # Level 8
        [8, "ancient icon", 2],
        # Level 9
        [9, "hueycoatl hide", 2],
    ]

# Crafting Guild - For enhancing crafting resources
[assets.crafting_guild]
    name = "Crafting Guild"
    description = "Multiplies gem drops"
    starting_level = 1
    max_level = 9
    icon = "🧵"

    # Upgrade requirements for Slayer Master by level
    upgrade_costs = [
        [1, "coins", 1000],
        [1, "pure essence", 500],
        # Level 2
        [2, "scurrius' spine", 1],
        # Level 3
        [3, "blighted manta ray", 200],
        # Level 4
        [4, "splitbark body", 1],
        # Level 5
        [5, "coins", 50000],
        # Level 6
        [6, "tzhaar-ket-om", 1],
        # Level 7
        [7, "dynamite", 500],
        # Level 8
        [8, "dragon boots", 2],
        # Level 9
        [9, "$category:any quartz", 2],
    ]

[assets.garrisons]
    name = "Garrisons"
    description = "Allows you to access drops from raids."
    starting_level = 1
    max_level = 5
    icon = "🏯"

    upgrade_costs = [
        # Level 2 - lunar chests
        [2, "$category:leaf-bladed items", 3],
        [2, "blood shard", 1],
        [2, "bronze bar", 25],
        # Level 3 - colosseum
        [3, "granite legs", 1],
        [3, "rune hasta", 25],
        [3, "$category:runes", 5000],
        [3, "sarachnis cudgel", 1],
        # Level 4 - toa
        [4, "unsired", 2],
        [4, "dragon pickaxe", 2],
        [4, "dragon chainbody", 1],
        [4, "dragon platelegs", 20],
        [4, "dragon med helm", 5],
        [4, "$category:logs", 10000],
        [4, "shield left half", 1],
        # Level 5 - cox
        [5, "fedora", 1],
        [5, "spirit shield", 1],
        [5, "$category:gems", 1337],
        [5, "$category:malediction/odium shards", 10],
        # Level 5 - tob
        [6, "fedora", 1],
        [6, "spirit shield", 1],
        [6, "mist rune", 6969],
        [6, "$category:malediction/odium shards", 5],
        [6, "occult necklace", 2],
    ] # Upgrade requirements for Garrisons by level
