[[resource_pattern]]
    pattern = ".*bones"
    category = "bones"

[[resource_pattern]]
    pattern = "coal"
    category = "ores"

[[resource_pattern]]
    pattern = ".* ore"
    category = "ores"

[[resource_pattern]]
    pattern = "clay"
    category = "ores"

[[resource_pattern]]
    pattern = ".* seed"
    category = "seeds"

[[resource_pattern]]
    pattern = "coins"
    category = "coins"

[[resource_pattern]]
    pattern = ".* rune"
    category = "runes"

[[resource_pattern]]
    pattern = "(grimy )?(guam|marrentill|tarromin|harralander|ranarr|toadflax|irit|avantoe|kwuarm|snapdragon|cadantine|lantadyme|dwarf weed|torstol)"
    category = "herbs"

[[resource_pattern]]
    pattern = "(uncut )?(sapphire|emerald|ruby|diamond|dragonstone|onyx)"
    category = "gems"


[[resource_pattern]]
    pattern = ".*"    # catchall, must be last
    category = "misc"
